[profile.default]
src = "src"
out = "out"
libs = ["lib"]
eth_rpc_url = "https://eth-mainnet.alchemyapi.io/v2/AlofYxI4lE118qazFGdPt5sL8VoMvddY"
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v3-periphery/=lib/v3-periphery/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


# forge test --fork-url https://eth-mainnet.alchemyapi.io/v2/YOUR-API-KEY

# forge test --gas-report

# forge coverage


# forge build
# forge test

